package report

import (
	"fmt"
	"strings"

	"github.com/Frank-Li-Yixuan/gh-flakefinder/internal/detect"
)

func Markdown(repository string, suspects []detect.Suspect) string {
	var b strings.Builder
	fmt.Fprintf(&b, "# Flaky CI suspects\n\n")
	fmt.Fprintf(&b, "Generated by gh-flakefinder for `%s`.\n\n", repository)
	if len(suspects) == 0 {
		fmt.Fprintf(&b, "No likely flaky workflow or job signals matched the selected scan window.\n")
		return b.String()
	}
	for i, suspect := range suspects {
		name := suspect.WorkflowName
		if suspect.JobName != "" {
			name += " / " + suspect.JobName
		}
		fmt.Fprintf(&b, "## %d. %s - confidence %.2f\n\n", i+1, name, suspect.Confidence)
		fmt.Fprintf(&b, "Signal: same head SHA `%s`, workflow `%s`, conclusion changed from `%s`.\n\n", shortSHA(suspect.HeadSHA), suspect.WorkflowName, suspect.Signal)
		fmt.Fprintf(&b, "Evidence:\n")
		for _, evidence := range suspect.Evidence {
			fmt.Fprintf(&b, "- %s: %s\n", evidence.Label, evidence.URL)
		}
		fmt.Fprintf(&b, "\n")
		fmt.Fprintf(&b, "Context:\n")
		fmt.Fprintf(&b, "- Branch: `%s`\n", suspect.Branch)
		fmt.Fprintf(&b, "- Event: `%s`\n", suspect.Event)
		fmt.Fprintf(&b, "- Category: `%s`\n", suspect.Category)
		fmt.Fprintf(&b, "- Observed attempts/runs: `%d`\n\n", suspect.Attempts)
		fmt.Fprintf(&b, "Suggested next actions:\n")
		fmt.Fprintf(&b, "- %s\n", suspect.Suggestion)
		fmt.Fprintf(&b, "- Add retries only after filing and linking a tracking issue.\n\n")
	}
	return b.String()
}
