package report_test

import (
	"encoding/json"
	"strings"
	"testing"

	"github.com/Frank-Li-Yixuan/gh-flakefinder/internal/detect"
	"github.com/Frank-Li-Yixuan/gh-flakefinder/internal/report"
)

func TestRenderMarkdownIsIssueReadyAndIncludesEvidenceLinks(t *testing.T) {
	out := report.Markdown("owner/repo", sampleSuspects())

	for _, want := range []string{
		"# Flaky CI suspects",
		"Generated by gh-flakefinder for `owner/repo`.",
		"## 1. CI / test-node-20-linux - confidence 0.90",
		"- Failed: https://github.com/owner/repo/actions/runs/1001/job/5001",
		"- Passed after rerun: https://github.com/owner/repo/actions/runs/1002/job/5002",
		"Suggested next actions:",
	} {
		if !strings.Contains(out, want) {
			t.Fatalf("markdown output missing %q:\n%s", want, out)
		}
	}
}

func TestRenderJSONIsDeterministic(t *testing.T) {
	out, err := report.JSON("owner/repo", sampleSuspects())
	if err != nil {
		t.Fatalf("JSON returned error: %v", err)
	}

	var decoded struct {
		Repository   string           `json:"repository"`
		GeneratedBy  string           `json:"generated_by"`
		SuspectCount int              `json:"suspect_count"`
		Suspects     []detect.Suspect `json:"suspects"`
	}
	if err := json.Unmarshal([]byte(out), &decoded); err != nil {
		t.Fatalf("invalid JSON: %v\n%s", err, out)
	}
	if decoded.Repository != "owner/repo" || decoded.GeneratedBy != "gh-flakefinder" || decoded.SuspectCount != 1 {
		t.Fatalf("unexpected JSON envelope: %#v", decoded)
	}
	if strings.Contains(out, "generated_at") {
		t.Fatalf("JSON must be deterministic and not include timestamps:\n%s", out)
	}
}

func TestRenderJSONUsesEmptyArrayWhenNoSuspects(t *testing.T) {
	out, err := report.JSON("owner/repo", nil)
	if err != nil {
		t.Fatalf("JSON returned error: %v", err)
	}
	if !strings.Contains(out, `"suspects": []`) {
		t.Fatalf("expected empty suspects array, got:\n%s", out)
	}
	if strings.Contains(out, `"suspects": null`) {
		t.Fatalf("JSON must not encode nil suspect slices as null:\n%s", out)
	}
}

func TestRenderTableContainsCompactSummary(t *testing.T) {
	out := report.Table("owner/repo", 30, sampleSuspects())

	for _, want := range []string{
		"Suspected flaky GitHub Actions jobs in owner/repo, last 30 days",
		"CONF  WORKFLOW",
		"0.90  CI",
		"failure -> success",
		"Run with --format markdown to create a report for an issue.",
	} {
		if !strings.Contains(out, want) {
			t.Fatalf("table output missing %q:\n%s", want, out)
		}
	}
}

func TestRenderTableHandlesNoSuspects(t *testing.T) {
	out := report.Table("owner/repo", 30, nil)

	for _, want := range []string{
		"Suspected flaky GitHub Actions jobs in owner/repo, last 30 days",
		"No likely flaky workflow or job signals matched the selected scan window.",
	} {
		if !strings.Contains(out, want) {
			t.Fatalf("table output missing %q:\n%s", want, out)
		}
	}
}

func sampleSuspects() []detect.Suspect {
	return []detect.Suspect{
		{
			WorkflowName: "CI",
			WorkflowID:   10,
			JobName:      "test-node-20-linux",
			HeadSHA:      "abc123456789",
			Branch:       "main",
			Event:        "push",
			Signal:       "failure -> success",
			Category:     "flaky-test",
			Confidence:   0.90,
			Suggestion:   "Inspect test isolation and shared state.",
			Evidence: []detect.EvidenceLink{
				{Label: "Failed", URL: "https://github.com/owner/repo/actions/runs/1001/job/5001", Conclusion: "failure"},
				{Label: "Passed after rerun", URL: "https://github.com/owner/repo/actions/runs/1002/job/5002", Conclusion: "success"},
			},
		},
	}
}
