package cmd_test

import (
	"bytes"
	"strings"
	"testing"

	appcmd "github.com/Frank-Li-Yixuan/gh-flakefinder/internal/cmd"
)

func TestScanFixtureJSONCommand(t *testing.T) {
	var stdout, stderr bytes.Buffer

	code := appcmd.Execute([]string{"scan", "--fixture", "../../testdata/workflow_runs.json", "--format", "json"}, &stdout, &stderr)

	if code != 0 {
		t.Fatalf("expected exit code 0, got %d\nstderr:\n%s", code, stderr.String())
	}
	out := stdout.String()
	if !strings.Contains(out, `"suspect_count": 4`) {
		t.Fatalf("expected deterministic JSON with four suspects:\n%s", out)
	}
	if !strings.Contains(out, `"workflow_name": "CI"`) || !strings.Contains(out, `"signal": "timed_out -> success"`) {
		t.Fatalf("expected CI and timed_out suspects:\n%s", out)
	}
}

func TestIssueDefaultsToDryRunMarkdown(t *testing.T) {
	var stdout, stderr bytes.Buffer

	code := appcmd.Execute([]string{"issue", "--fixture", "../../testdata/workflow_runs.json", "--format", "markdown"}, &stdout, &stderr)

	if code != 0 {
		t.Fatalf("expected exit code 0, got %d\nstderr:\n%s", code, stderr.String())
	}
	out := stdout.String()
	for _, want := range []string{
		"# Flaky CI suspects",
		"Generated by gh-flakefinder",
		"Dry run only. No issue was created.",
	} {
		if !strings.Contains(out, want) {
			t.Fatalf("issue dry-run output missing %q:\n%s", want, out)
		}
	}
}

func TestInvalidFormatReturnsUsefulError(t *testing.T) {
	var stdout, stderr bytes.Buffer

	code := appcmd.Execute([]string{"scan", "--fixture", "../../testdata/workflow_runs.json", "--format", "xml"}, &stdout, &stderr)

	if code == 0 {
		t.Fatalf("expected non-zero exit code")
	}
	if !strings.Contains(stderr.String(), "unsupported format") {
		t.Fatalf("expected unsupported format error, got:\n%s", stderr.String())
	}
}

func TestScanHelpExitsSuccessfully(t *testing.T) {
	var stdout, stderr bytes.Buffer

	code := appcmd.Execute([]string{"scan", "--help"}, &stdout, &stderr)

	if code != 0 {
		t.Fatalf("expected exit code 0, got %d\nstderr:\n%s", code, stderr.String())
	}
	if strings.Contains(stderr.String(), "error: flag: help requested") {
		t.Fatalf("help should not be reported as an error:\n%s", stderr.String())
	}
	if !strings.Contains(stderr.String(), "Usage of scan:") || !strings.Contains(stderr.String(), "-repo string") {
		t.Fatalf("expected scan help text, got stdout:\n%s\nstderr:\n%s", stdout.String(), stderr.String())
	}
}

func TestIssueHelpExitsSuccessfully(t *testing.T) {
	var stdout, stderr bytes.Buffer

	code := appcmd.Execute([]string{"issue", "--help"}, &stdout, &stderr)

	if code != 0 {
		t.Fatalf("expected exit code 0, got %d\nstderr:\n%s", code, stderr.String())
	}
	if strings.Contains(stderr.String(), "error: flag: help requested") {
		t.Fatalf("help should not be reported as an error:\n%s", stderr.String())
	}
	if !strings.Contains(stderr.String(), "Usage of issue:") || !strings.Contains(stderr.String(), "-create") {
		t.Fatalf("expected issue help text, got stdout:\n%s\nstderr:\n%s", stdout.String(), stderr.String())
	}
}
